// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHr8JTH_GLLhQ8B_X90lnANTE3j_cXSjA',
    appId: '1:98010296393:web:5ca711b5c53f9ae214cf98',
    messagingSenderId: '98010296393',
    projectId: 'lumina-pushpal',
    authDomain: 'lumina-pushpal.firebaseapp.com',
    storageBucket: 'lumina-pushpal.firebasestorage.app',
    measurementId: 'G-LTJKCBYHJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkOC9PnVzQy38cB0kjUn0E0501vR2Blow',
    appId: '1:98010296393:android:6aef7e013d60a67b14cf98',
    messagingSenderId: '98010296393',
    projectId: 'lumina-pushpal',
    storageBucket: 'lumina-pushpal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQb4-HhZrXnonSJ_-NDPq3bGxUN1rJIt8',
    appId: '1:98010296393:ios:e947c0c7d632ad9b14cf98',
    messagingSenderId: '98010296393',
    projectId: 'lumina-pushpal',
    storageBucket: 'lumina-pushpal.firebasestorage.app',
    iosBundleId: 'com.example.pushPal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQb4-HhZrXnonSJ_-NDPq3bGxUN1rJIt8',
    appId: '1:98010296393:ios:e947c0c7d632ad9b14cf98',
    messagingSenderId: '98010296393',
    projectId: 'lumina-pushpal',
    storageBucket: 'lumina-pushpal.firebasestorage.app',
    iosBundleId: 'com.example.pushPal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHr8JTH_GLLhQ8B_X90lnANTE3j_cXSjA',
    appId: '1:98010296393:web:99e35e88efe1879914cf98',
    messagingSenderId: '98010296393',
    projectId: 'lumina-pushpal',
    authDomain: 'lumina-pushpal.firebaseapp.com',
    storageBucket: 'lumina-pushpal.firebasestorage.app',
    measurementId: 'G-J9TT28PSQX',
  );
}
