import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:push_pal/firebase_options.dart'; // Generated by FlutterFire
import 'package:push_pal/src/routing/app_router.dart'; // Import the app router
import 'package:push_pal/src/theme/app_theme.dart'; // Import the app theme

// The GlobalKey for navigator is now managed by GoRouter (e.g., _rootNavigatorKey in app_router.dart)
// final GlobalKey<NavigatorState> _navigatorKey = GlobalKey<NavigatorState>(); // This line can be removed

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends ConsumerWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return MaterialApp.router(
      routerConfig: appRouter, // Use the router configuration
      title: 'PushPal Fitness Buddy',
      theme: appThemeData, // Apply the app theme
      debugShowCheckedModeBanner: false,
    );
  }
}

// Placeholder for the initial screen
// This HomeScreen is now routed to by GoRouter.
// TODO: Move HomeScreen to its own file (e.g., lib/src/features/home/presentation/home_screen.dart)
class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('PushPal Home'), // Will now use AppBarTheme from app_theme.dart
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Text(
              'Welcome to PushPal! Authentication coming soon.',
              // style: Theme.of(context).textTheme.bodyLarge, // Example of using themed text
            ),
            const SizedBox(height: 20),
            ElevatedButton(
              onPressed: () {},
              child: const Text('Sample Button'), // Will use ElevatedButtonTheme
            )
          ],
        ),
      ),
    );
  }
}
