import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:push_pal/firebase_options.dart'; // Generated by FlutterFire
import 'package:push_pal/src/routing/app_router.dart'; // Import the app router
import 'package:push_pal/src/theme/app_theme.dart'; // Import the app theme

// The GlobalKey for navigator is now managed by GoRouter (e.g., _rootNavigatorKey in app_router.dart)
// final GlobalKey<NavigatorState> _navigatorKey = GlobalKey<NavigatorState>(); // This line can be removed

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends ConsumerWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return MaterialApp.router(
      routerConfig: appRouter, // Use the router configuration
      title: 'PushPal Fitness Buddy',
      theme: appThemeData, // Apply the app theme
      debugShowCheckedModeBanner: false,
    );
  }
}

// HomeScreen has been moved to lib/src/features/home/presentation/home_screen.dart
